"""Pydantic API contracts for the RAG AI Quality Assistant chat endpoint."""

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field

from models.chat import ChatRole


class ChatCitation(BaseModel):
    """Source citation from LanceDB vector retrieval."""

    source_type: str = Field(description="Type of source record (inspection_result, batch_summary, report)")
    source_id: UUID = Field(description="ID of the source domain entity")
    batch_id: UUID = Field(description="Associated batch ID")
    content: str = Field(description="Retrieved inspection content snippet")
    distance: float = Field(description="Vector distance score (lower is closer)")


class ChatRequest(BaseModel):
    """User question request payload."""

    message: str = Field(min_length=1, max_length=5000, description="Inspector question regarding quality or inspection results")
    session_id: UUID | None = Field(default=None, description="Optional existing chat session ID to maintain conversation context")
    batch_id: UUID | None = Field(default=None, description="Optional batch ID filter to constrain vector search")
    top_k: int | None = Field(default=None, ge=1, le=20, description="Optional custom Top-K retrieval count")


class ChatResponse(BaseModel):
    """Grounded assistant response with sources and updated summary."""

    session_id: UUID = Field(description="Chat session ID")
    message: str = Field(description="Grounded response generated by the AI Quality Assistant")
    retrieved_sources: list[ChatCitation] = Field(default_factory=list, description="Top-K vector search citations used for context")
    summary: str | None = Field(default=None, description="Current rolling conversation summary")


class ChatMessageResponse(BaseModel):
    """Single message response item for history endpoint."""

    id: UUID
    session_id: UUID
    role: ChatRole
    content: str
    created_at: datetime


class ChatSessionResponse(BaseModel):
    """Session overview response item."""

    id: UUID
    batch_id: UUID | None = None
    title: str
    summary: str
    created_at: datetime
    updated_at: datetime
    messages: list[ChatMessageResponse] = Field(default_factory=list)
